version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

[[analyzers]]
enabled = true
name = "shell"

[[analyzers]]
enabled = true
name = "secrets"

[[analyzers]]
dependency_file_paths = [
  "pyproject.toml",
  "poetry.lock"
]
enabled = true
name = "python"

[analyzers.meta]
max_line_length = 88
runtime_version = "3.x.x"
skip_doc_coverage = ["magic", "init"]
type_checker = "mypy"

[[transformers]]
enabled = true
name = "black"
