version = 1

test_patterns = [
  "tests/**",
  "test_*.py",
]

[[analyzers]]
enabled = true
name = "shell"

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
enabled = true
name = "python"
dependency_file_paths = [
  "pyproject.toml",
  "poetry.lock",
]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 88w
  skip_doc_coverage = ["magic", "init"]

[[transformers]]
enabled = true
name = "black"
