version = 1

test_patterns = [
  "tests/**",
  "test_*.py",
]

[[analyzers]]
enabled = true
name = "shell"

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
enabled = true
name = "python"

[[transformers]]
enabled = true
name = "black"
