[tool.poetry]
authors = ["Katolus <pkatolik@healthshare.com.au>"]
description = ""
name = "functions"
readme = "README.md"
version = "0.1.0"

[tool.poetry.scripts]
functions = "functions.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"
pydantic = "^1.8.2"
docker = "^5.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"
black = {version = "^21.8b0", allow-prereleases = true}

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
