name: 👑 Feature request
description: If you are thinking about a new feature prospect.
title: "[Feature]: ..."
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this feature request.

        Please make sure that you run your idea through the [community](https://github.com/Katolus/functions/discussions/categories/ideas).
  - type: textarea
    id: problem
    attributes:
      label: The Problem
      description: |
        ## Is your feature request related to a problem? Please describe.

        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      render: markdown
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: The Proposal
      description: |
        ## Describe the solution you'd like. Don't spare your vision.

        A clear and concise description of what you want to happen.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: The Alternatives
      description: |
        ## Describe alternatives you've considered.

        A clear and concise description of any alternative solutions or features you've considered.      render: markdown
    validations:
      required: false
  - type: textarea
    id: value
    attributes:
      label: The Value
      description: |
        ## Describe what value this feature brings to the project.

        Try to enumerate the values that the change will bring to the project.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
        label: Additional Context
        description: |
            Add any other context or screenshots about the feature request here.

            Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
